greeting:
  message: "hello"

quarkus:
  native:
    # if needed add -H:+UnlockExperimentalVMOptions
    additional-build-args: -H:IncludeResources=venus-sample-init-with-parameters/fm-doc-process-config.xml,\
      -H:IncludeResources=venus-sample-init-with-parameters/template/document.ftl